# Generated by Django 5.2.7 on 2026-06-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('linkedin_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('industry', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Soft Skill', 'Soft Skill'), ('Other', 'Other')], default='Other', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_job_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], default='On-site', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('experience_level', models.CharField(blank=True, choices=[('Entry', 'Entry Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior Level'), ('Lead', 'Lead'), ('Director', 'Director')], max_length=50)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='jobs.company')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(blank=True, through='jobs.JobSkill', to='jobs.skill'),
        ),
        migrations.CreateModel(
            name='UserJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='jobs.jobpost')),
            ],
            options={
                'verbose_name': 'User Job Status',
                'verbose_name_plural': 'User Job Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['date_posted'], name='jobs_jobpos_date_po_ec4267_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['work_type'], name='jobs_jobpos_work_ty_02a45a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='jobs_jobpos_status_b64ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_active'], name='jobs_jobpos_is_acti_847a9a_idx'),
        ),
    ]
