# Generated by Django 5.2.7 on 2026-07-05 13:29

from django.db import migrations, models


def populate_source_job_ids(apps, schema_editor):
    JobPost = apps.get_model('jobs', 'JobPost')
    for job in JobPost.objects.filter(source='linkedin', source_job_id='', linkedin_job_id__isnull=False):
        job.source_job_id = job.linkedin_job_id
        job.source_url = job.apply_url or ''
        job.save(update_fields=['source_job_id', 'source_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='match_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='match_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='resume_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('bdjobs', 'BDJobs'), ('chakri', 'Chakri'), ('skill_jobs', 'Skill.jobs'), ('company', 'Company Career Page'), ('manual', 'Manual Import'), ('other', 'Other')], db_index=True, default='linkedin', max_length=30),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='resume_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='linkedin_job_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('shortlisted', 'Shortlisted'), ('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('ignored', 'Ignored')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='userjobstatus',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('shortlisted', 'Shortlisted'), ('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('ignored', 'Ignored')], default='new', max_length=20),
        ),
        migrations.RunPython(populate_source_job_ids, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['source', 'source_job_id'], name='jobs_jobpos_source_cb839c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['application_deadline'], name='jobs_jobpos_applica_c29bea_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['match_score'], name='jobs_jobpos_match_s_34f233_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('source_job_id', ''), _negated=True), fields=('source', 'source_job_id'), name='unique_job_per_source'),
        ),
    ]
