# Generated by Django 5.2.7 on 2026-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_userpreference_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for revocation on force stop', max_length=255, null=True),
        ),
    ]
